### ISSUE TITLE
How to use fast_gui?

### ISSUE THREAD

**Issue by Lin-plax** [asvcode/Vision_UI#4]
The fast_gui is different from the Vision_UI, how to use it?

**Comment by asvcode** [comment]
Currently there may be some very minor differences between `fast-gui` and `Vision_UI`.  `fast-gui` is configured to work with `fastai2` and you would use it the same way as `Vision_UI`.  I do need to update the documentation so that it is easier to use.

`!pip install fast-gui`

```
from vision_ui2 import*
display_ui()
```

should lead you to this gui:
![gui](https://user-images.githubusercontent.com/25020209/87564064-cdd4c200-c674-11ea-9336-70e930174c15.PNG)

Let me know if this helps?

Thanks

**Comment by Lin-plax** [comment]
Thanks for your helps!
Here are  the picture of problems:
[image: image.png]
And I have check the source code:
[image: image.png]
There are no the model named vision_ui2. But I found in the github code :
[image: image.png]
It has the model named vision_ui2.

Thanks for your helps again.

asvcode <notifications@github.com> 于2020年7月15日周三 下午11:50写道：

**Comment by asvcode** [comment]
Unfortunately the pictures  you posted are not displaying.  Any chance you can upload them again?  Thanks

**Comment by asvcode** [comment]
Closing this issue, please let me know if you have any further questions.
